import Layout from '../components/layout/Layout'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/global.css'

import { Create } from '@mui/icons-material'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Layout>
      <body className={inter.className}>{children}
      </body>
      </Layout>
    </html>
  )
}
